In [1]:
print("Hello")

Hello


In [2]:
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [6]:
# Get Dimension
a.ndim

1

In [8]:
# Get Shape
b.shape

(2, 3)

In [10]:
a.dtype

dtype('int32')

In [12]:
# Get Size
a.itemsize

4

In [14]:
# Get total size 
a.nbytes

12